services:
  cali:
    extends:
      file: docker-compose-gui.yaml
      service: cali
    container_name: cali
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia